spring:
  # h2 db settings
  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    url: jdbc:h2:~/testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
    platform: h2
    
  # enable h2 web console
  h2:
    console:
      enabled: true
      path: /console
      
  # jpa settings
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  # ehcache 3 configuration
  # commented out b/c setting up programmatically
  #cache:
  #  jcache:
  #    config: ehcache3.xml